### ISSUE TITLE
Enable HTTPS on github pages

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads-wiki#14]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by osresearch** [comment]
I've deleted the CNAME and re-added it, so hopefully that will kick off the SSL key generation.

**Comment by persmule** [comment]
It seems that osresearch.net cannot be resolved as a CNAME of <somedomain>.github.io, but points to a fastly CDN.

**Comment by persmule** [comment]
As an example, <https://www.dcandroid.org> does work, while `www.dcandroid.org` is a CNAME of `dcandroid.github.io`, and its certificate comes from Let's Encrypt.

**Comment by tlaurion** [comment]
@osresearch : http://osresearch.net/ is http only.

**Comment by flawedworld** [comment]
@osresearch Apologies for @ing but any progress?

DNS records seem to be okay, in the repo setting HTTPS must be enabled manually, is this on? HTTPS will not start automatically otherwise. This is somewhat crucial for a security project.

**Comment by Thrilleratplay** [comment]
@osresearch https://osresearch.net/ returns Error code: SSL_ERROR_BAD_CERT_DOMAIN

Reading through [Github pages docs](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site), I ran the `dig` command as suggested.
```
$> dig osresearch.net +nostats +nocomments +nocmd                                                                                                                                                 [11:49:30]
;osresearch.net.			IN	A
osresearch.net.		14400	IN	A	151.101.64.133
osresearch.net.		14400	IN	A	151.101.192.133
osresearch.net.		14400	IN	A	151.101.0.133
osresearch.net.		14400	IN	A	151.101.128.133
osresearch.net.		172800	IN	NS	ns2.swcp.com.
osresearch.net.		172800	IN	NS	kitsune.swcp.com.
```

I think `osresearch.github.io` is missing from that list.  The custom domain or Enforce HTTPS may not be set.

**Comment by tlaurion** [comment]
poked @osresearch over slack.

**Comment by georgeowell** [comment]
Cmon folks. I'm saying this with love but I think a website on this topic should have HTTPS :smile_cat:

**Comment by Thrilleratplay** [comment]
@tlaurion @osresearch Perhaps, seeing that [github.com/osresearch](https://github.com/osresearch) is more than just Heads ROM, maybe Heads should have a domain registered that is specific to this project.

**Comment by tlaurion** [comment]
Re-poked.

**Comment by tlaurion** [comment]
"Looks like it is protected now. The issue was the A records pointed to an old version of the GitHub servers, which were not supported by their ssl cert system"
