### ISSUE TITLE
dead links in wiki

### ISSUE THREAD

**Issue by cl445** [osresearch/heads-wiki#69]
All internal links at least at the index.md are pointing to nowhere (404).

**Comment by Thrilleratplay** [comment]
@cl445  Are you linking through the markdown file in this repo or navigating through https://osresearch.net?  The links within the markdown files are intended to processed through Jekyll and hosted, not browsed within the github repo.

**Comment by cl445** [comment]
Yes, this what I did unintentionally. I understand that this could not work. 
The fact that confuse me is that the README.md from the heads repository is pointing to the index.md in this repo. 
Wouldn't it be a better idea to change the link to a working version? Or at least not to link to the Index.md but only to the repository?

**Comment by Thrilleratplay** [comment]
@cl445  Agreed and didn't realize that link existed.  I put in a [PR to change that](https://github.com/osresearch/heads/pull/986).  Sorry for the confusion.
